GET    http://localhost:4000/app/signupCustomer
Content-Type: application/json

{
    "fullName":"Professional",
    "email":"p@g.com",
    "phoneNo":"7789987898",
    "gender":"male",
    "occupation":"student",
    "password":"123",
    "experience":"4 years"

}