POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "fullName":"vamshi",
    "email":"v@g.com",
    "phoneNo":"7789987898",
    "gender":"male",
    "occupation":"student",
    "password":"vamshipass",
    "experience":"none"

}